### ISSUE TITLE
Query on Metrics Reported in VSR Sub-Project Test Phase

### ISSUE THREAD

**Issue by RookieJunChen** [ddlBoJack/SLAM-LLM#95]
### System Info

Excellent work! May I kindly inquire what metrics are reported in the test phase of the VSR sub-project? Is it WER?

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Excellent work! May I kindly inquire what metrics are reported in the test phase of the VSR sub-project? Is it WER?

### Error logs

Excellent work! May I kindly inquire what metrics are reported in the test phase of the VSR sub-project? Is it WER?

### Expected behavior

More details.

**Comment by ddlBoJack** [comment]
Yes, it's WER metrics.

**Comment by hanif-rt** [comment]
Hey Guys, did you guys do any other experiments for VSR?

Seems quite promising that a simple linear projector finetuning + adapter instruction tuning does so well (29.4% compared to based 27.8% for avhubert large).

Have you guys tried any other approaches?
